package main

import (
	"context"
	"crypto/tls"
	"errors"
	"log/slog"
	"net/http"
	"os"
	"time"

	"github.com/saveenergy/openbyte/internal/api"
	"github.com/saveenergy/openbyte/internal/config"
	"github.com/saveenergy/openbyte/internal/results"
	"github.com/saveenergy/openbyte/internal/tlsutil"
)

func setupRuntimeResources(cfg *config.Config) (http.Handler, *results.Store, error) {
	if err := os.MkdirAll(cfg.DataDir, 0755); err != nil {
		slog.Error("Failed to create data directory", "error", err)
		return nil, nil, err
	}
	resultsStore, err := results.New(cfg.DataDir+"/results.db", cfg.MaxStoredResults)
	if err != nil {
		slog.Error("Failed to open results store", "error", err)
		return nil, nil, err
	}
	slog.Info("Results store opened",
		"path", cfg.DataDir+"/results.db",
		"max_results", cfg.MaxStoredResults)

	router := api.NewRouter(cfg, resultsStore)
	return router.SetupRoutes(), resultsStore, nil
}

func startHTTPServer(cfg *config.Config, srv *http.Server, srvErrCh chan<- error) {
	go func() {
		err := serveHTTPOrTLS(cfg, srv)
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			srvErrCh <- err
		}
	}()
}

func serveHTTPOrTLS(cfg *config.Config, srv *http.Server) error {
	slog.Info("Server starting", "address", cfg.BindAddress+":"+cfg.Port)
	if cfg.TLSCertFile != "" && cfg.TLSKeyFile != "" {
		return srv.ListenAndServeTLS(cfg.TLSCertFile, cfg.TLSKeyFile)
	}
	if cfg.TLSAutoGen {
		if err := configureAutogeneratedTLS(srv); err != nil {
			return err
		}
		slog.Info("TLS auto-generation enabled; serving HTTPS with an ephemeral self-signed certificate")
		return srv.ListenAndServeTLS("", "")
	}
	return srv.ListenAndServe()
}

func configureAutogeneratedTLS(srv *http.Server) error {
	cert, err := tlsutil.SelfSignedLocalhost()
	if err != nil {
		return err
	}
	ensureTLSConfig(srv).Certificates = []tls.Certificate{cert}
	return nil
}

func ensureTLSConfig(srv *http.Server) *tls.Config {
	if srv.TLSConfig == nil {
		srv.TLSConfig = &tls.Config{}
	}
	return srv.TLSConfig
}

func waitForShutdown(quit <-chan os.Signal, srvErrCh <-chan error) int {
	select {
	case sig := <-quit:
		slog.Info("Shutting down server...", "signal", sig.String())
		return exitSuccess
	case err := <-srvErrCh:
		slog.Error("Server failed", "error", err)
		return exitFailure
	}
}

func shutdownHTTPServer(srv *http.Server, timeout time.Duration) {
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	if err := srv.Shutdown(ctx); err != nil {
		slog.Error("Server shutdown error", "error", err)
	}
}
