package server

import (
	"net/http"
	"testing"
)

func TestConfigureAutogeneratedTLSInstallsCertificate(t *testing.T) {
	srv := &http.Server{}
	if err := configureAutogeneratedTLS(srv); err != nil {
		t.Fatalf("configure generated TLS: %v", err)
	}
	if srv.TLSConfig == nil {
		t.Fatal("TLSConfig is nil")
	}
	if len(srv.TLSConfig.Certificates) != 1 {
		t.Fatalf("certificates len = %d, want 1", len(srv.TLSConfig.Certificates))
	}
	if len(srv.TLSConfig.Certificates[0].Certificate) == 0 {
		t.Fatal("generated certificate chain is empty")
	}
}
