package server

import (
	"context"
	"crypto/tls"
	"errors"
	"net/http"
	"os"
	"time"

	"github.com/saveenergy/openbyte/internal/api"
	"github.com/saveenergy/openbyte/internal/config"
	"github.com/saveenergy/openbyte/internal/logging"
	"github.com/saveenergy/openbyte/internal/results"
	"github.com/saveenergy/openbyte/internal/tlsutil"
)

type serverResources struct {
	resultsStore *results.Store
}

func (r *serverResources) stopAll(pprofServer *http.Server) {
	if r.resultsStore != nil {
		r.resultsStore.Close()
	}
	shutdownPprofServer(pprofServer, 5*time.Second)
}

func setupRuntimeResources(cfg *config.Config, resources *serverResources) (http.Handler, error) {
	if err := os.MkdirAll(cfg.DataDir, 0755); err != nil {
		logging.Error("Failed to create data directory", logging.Field{Key: "error", Value: err})
		return nil, err
	}
	var err error
	resources.resultsStore, err = results.New(cfg.DataDir+"/results.db", cfg.MaxStoredResults)
	if err != nil {
		logging.Error("Failed to open results store", logging.Field{Key: "error", Value: err})
		return nil, err
	}
	logging.Info("Results store opened",
		logging.Field{Key: "path", Value: cfg.DataDir + "/results.db"},
		logging.Field{Key: "max_results", Value: cfg.MaxStoredResults})

	router := api.NewRouter(cfg, resources.resultsStore)
	return router.SetupRoutes(), nil
}

func startHTTPServer(cfg *config.Config, srv *http.Server, srvErrCh chan<- error) {
	go func() {
		err := serveHTTPOrTLS(cfg, srv)
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			srvErrCh <- err
		}
	}()
}

func serveHTTPOrTLS(cfg *config.Config, srv *http.Server) error {
	logging.Info("Server starting", logging.Field{Key: "address", Value: cfg.BindAddress + ":" + cfg.Port})
	if cfg.TLSCertFile != "" && cfg.TLSKeyFile != "" {
		return srv.ListenAndServeTLS(cfg.TLSCertFile, cfg.TLSKeyFile)
	}
	if cfg.TLSAutoGen {
		if err := configureAutogeneratedTLS(srv); err != nil {
			return err
		}
		logging.Info("TLS auto-generation enabled; serving HTTPS with an ephemeral self-signed certificate")
		return srv.ListenAndServeTLS("", "")
	}
	return srv.ListenAndServe()
}

func configureAutogeneratedTLS(srv *http.Server) error {
	cert, err := tlsutil.SelfSignedLocalhost()
	if err != nil {
		return err
	}
	ensureTLSConfig(srv).Certificates = []tls.Certificate{cert}
	return nil
}

func ensureTLSConfig(srv *http.Server) *tls.Config {
	if srv.TLSConfig == nil {
		srv.TLSConfig = &tls.Config{}
	}
	return srv.TLSConfig
}

func waitForShutdown(quit <-chan os.Signal, srvErrCh <-chan error) int {
	select {
	case sig := <-quit:
		logging.Info("Shutting down server...", logging.Field{Key: "signal", Value: sig.String()})
		return exitSuccess
	case err := <-srvErrCh:
		logging.Error("Server failed", logging.Field{Key: "error", Value: err})
		return exitFailure
	}
}

func shutdownHTTPServer(srv *http.Server, timeout time.Duration) {
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	if err := srv.Shutdown(ctx); err != nil {
		logging.Error("Server shutdown error", logging.Field{Key: "error", Value: err})
	}
}
